baseURL = 'http://tlecommunity.com/'
languageCode = 'en-us'
title = 'TLE Community'
theme = 'ananke'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 25
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Natalie McCallum"
  favicon = "http://localhost:3002/ui/favicon.png"
  site_logo = "http://localhost:3002/ui/logo.png"
  description = "Welcome to The Lacuna Expanse"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "github"
url = "https://github.com/tlecommunity"
